const fs = require('fs');

// Helper to remove accidental quotes if the user pasted them in Vercel UI
const cleanVar = (val) => (val || '').replace(/^['"]|['"]$/g, '').trim();

const supabaseUrl = cleanVar(process.env.SUPABASE_URL);
const supabaseKey = cleanVar(process.env.SUPABASE_ANON_KEY);
const joinCode = cleanVar(process.env.JOIN_CODE);

const envContent = `// Auto-generated by Vercel build script
window.env = {
  SUPABASE_URL: ${JSON.stringify(supabaseUrl)},
  SUPABASE_ANON_KEY: ${JSON.stringify(supabaseKey)},
  JOIN_CODE: ${JSON.stringify(joinCode)}
};
`;

fs.writeFileSync('./env.js', envContent);
console.log('env.js generated successfully with environment variables.');
