const fs = require('fs');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_ANON_KEY || '';
const joinCode = process.env.JOIN_CODE || '';

const envContent = `// Auto-generated by Vercel build script
window.env = {
  SUPABASE_URL: '${supabaseUrl}',
  SUPABASE_ANON_KEY: '${supabaseKey}',
  JOIN_CODE: '${joinCode}'
};
`;

fs.writeFileSync('./env.js', envContent);
console.log('env.js generated successfully with environment variables.');
